### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by kchawla-pi** [christosk92/Wavee#1]
Hi! Thanks for the project. I am excited!
Would you consider using GitHub actions to automatically build and the code and made available via Releases for people to quickly download and test?
I can do this, but I would rather not have to install the Visual Studio stack from one app, and most people may just bypass trying it out completely.

**Comment by christosk92** [comment]
Yeh I'll make sure you can just download the app from here, as well as from the MSFT store once it's done.

Sadly I was gone for a month because of work so I wasn't able to work on it for long. But I'll make sure to do that once it's done.

**Comment by OfficialAwesomeDude** [comment]
+1 would also love to test out and provide feedback before release

**Comment by christosk92** [comment]
Thanks for the feedback/idea.

I will make sure to release a binary ASAP once I get all the basics rolling. I expect this to be in the coming month.
