### ISSUE TITLE
just slide it

### ISSUE THREAD

**Issue by OfficialAwesomeDude** [christosk92/Wavee#10]
is it possible in any way for us to use the app still, even as a local music player app. what happened though? i have had this app in the back of my mind for the past 6 months as the spotify deskotp app gets worse and worse

**Comment by christosk92** [comment]
Honestly I think if I just remove the decryption part of my code, I'll still be able to publish a version as is. It's just that the motivation for the project hasn't been there. I'll see what I can do.

I've been working on it here and there to also support local files yes. 
Example:
![image](https://github.com/christosk92/Wavee/assets/13438702/61b4458d-4905-44c2-a3ea-f29e54d19703)
