### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ahmuro** [christosk92/Wavee#11]
Well what a bummer, I was really looking forward to this. Still, thanks for all the effort you put into this, so sorry to see it all go like this. Good luck.

**Comment by christosk92** [comment]
It is not over yet. 
After much consideration I have decided to continue with the project. However I will not make the source code for decoding Spotify tracks public.

**Comment by SeriousM** [comment]
> After much consideration I have decided to continue with the project. However I will not make the source code for decoding Spotify tracks public.

At least an interface definition would be helpful to have a guideline for implementation, just leave the keys out of the source.
one who wants to find the keys will be able to get it from other publipsshed projects anyway.

**Comment by christosk92** [comment]
> > After much consideration I have decided to continue with the project. However I will not make the source code for decoding Spotify tracks public.
> 
> At least an interface definition would be helpful to have a guideline for implementation, just leave the keys out of the source. one who wants to find the keys will be able to get it from other publipsshed projects anyway.

It's not only about the keys (the returned AES key is not obfuscated anyways), but about the method in general. Basically their tracks are "encrypted" using obfuscation. The trick is to figure out their obscure algorithm in which the AES keys work..

Well this is is only valid for the old AES key retrieved through TCP. 
The new playplay endpoint (HTTP), returns an obfuscated key. Thus needing to also de-obfuscate that one, which in itself is grounds for a DMCA. I am sorry but I cannot assist you in this further. 

Like you said, there are other resources (librespot somehow gets a pass?) that do have the decryption algorithm published.

Best of luck
