### ISSUE TITLE
Eventually using Flutter for easy development on all platforms.

### ISSUE THREAD

**Issue by kchawla-pi** [christosk92/Wavee#3]
Hi! Awesome project; looking forward to using it.
Changing stacks before even the first release can add so much work that it can kill the motivation to continue a project, so please don't do that.
But would you consider building the frontend using Flutter for your next release? Then the app can easily be used on MacOS, Windows, and Linux.
I am a purely backend dev but recently started learning Fluter to build a frontend for my work app. Still on the tutorials stage because the backend is the priority right now but Flutter was extremely easy to learn ad seems very powerful.

You clearly have great frontend and design chops, so it will probably be even easier for you, but the only tutorial that I managed to enjoy and learn from and stick with was https://fluttercrashcourse.com/

**Comment by christosk92** [comment]
I'm glad you're taking interest in the project!

As a matter of fact, I do some flutter stuff at work :).

Unfortunately it's not as easy to just migrate this project over to Flutter as they use a completely different stack. .NET is simply not compatible, and the backend for Spotify & local playback was completely made in C#. So a change to Flutter would mean a complete change in the project. 

The point of this project is to provide a native c# spotify client.

**Comment by SnowPowerCore** [comment]
Yeah, if this is the case, it's probably better to look into Uno platform (least amount of changes due to the principle of "Windows first, framework adapts everything to other platforms") or MAUI (harder than previous). There are also other options available inside of the .NET environment.

**Comment by FireCubeStudios** [comment]
MAUI, Avalonia, Uno, Xamarin, Blazor. lot of options in .NET. flutter is not needed imo

**Comment by kchawla-pi** [comment]
Cool! Good to know.
