### ISSUE TITLE
Release installer file

### ISSUE THREAD

**Issue by Jakeverse** [christosk92/Wavee#7]
I'm following this repo like 6 month+ and still we have not got any pre release/alpha/beta soo that we can test this app early. I know it will take time to make something perfect but I can't wait anymore to use this beautiful app. Please release installer file asap if you can. 🥺

**Comment by OfficialAwesomeDude** [comment]
Me too. Since I seen a Reddit post. Reslly tryna use this too

**Comment by christosk92** [comment]
Sorry guys..
Spotify recently killed a lot of endpoints I relied on, which is expected because it's not public information.. So I have to do a lot of rewrites.

**Comment by Jakeverse** [comment]
> Sorry guys.. Spotify recently killed a lot of API calls & endpoints I relied on ([librespot-org/librespot-java#678](https://github.com/librespot-org/librespot-java/issues/678)), which is expected because it's not public information.. So I have to do a lot of rewrites.
> 
> I am really trying my best. Plus I have been insanely busy with my real job lately.

Sad to hear spotify stopped those API Wavee used. Still you are doing a lot of work. You're really great person. I hope you will find a new way or workaround to fix these issue. We will wait till then. Thanks for replying. 😊

**Comment by OfficialAwesomeDude** [comment]
> Sorry guys.. Spotify recently killed a lot of API calls & endpoints I relied on ([librespot-org/librespot-java#678](https://github.com/librespot-org/librespot-java/issues/678)), which is expected because it's not public information.. So I have to do a lot of rewrites.
> 
> I am really trying my best. Plus I have been insanely busy with my real job lately.

It's honestly all good. Real job > side project. I think we just wanted to show some support again and that we are very much looking forward to it. Also thanks for the reply.

**Comment by christosk92** [comment]
Thanks guys, I really appreciate it. And I'm really looking forward to a release too :)

**Comment by christosk92** [comment]
also https://github.com/microsoft/WindowsAppSDK/issues/3305 is a major blocking issue for me right now.
I might be forced to use LibVLC, as the NAudio vorbis decoder kinda sucks (its optimized for files instead of web streaming).

**Comment by Jakeverse** [comment]
> also [microsoft/WindowsAppSDK#3305](https://github.com/microsoft/WindowsAppSDK/issues/3305) is a major blocking issue for me right now. I might be forced to use LibVLC, as the NAudio vorbis decoder kinda sucks (its optimized for files instead of web streaming). But of course, I'll lose out on all the native windows playback features such as transport controls and performance (LibVLC is interop so it might just break the whole app if it fails.)

😢

I'm not that knowledgeable in programming but LibVLC is good for now I think. This project uses it (https://github.com/huynhsontung/Screenbox). I hope that this bug will be fixed by MS asap.. Thank you so much for working so hard. 🥺
